@baseUrl = https://api.dev.talkieappserver.xyz
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/chat/message/conversation-list
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/chat/message/user/<receiverId>
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/chat/message
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "conversationId": "",
  "receiverId": "",
  "receiverUsername": "Drilll",
  "receiverAvatarColor": "black",
  "receiverProfilePicture": "https://res.cloudinary.com/doyg3ppyn/image/upload/v1694553332/6500d4f335bfbe09d052e354",
  "body": "Hi there this is the first test",
  "gifUrl": "",
  "isRead": false,
  "selectedImage": ""
}

###
POST {{baseUrl}}/{{urlPath}}/chat/message/add-chat-users
Content-Type: application/json
Accept: application/json
withCredentials: true
# user one is the loged in user usertwo is the one you want to add to the chat
{
  "userOne": "",
  "userTwo": ""
}

###
POST {{baseUrl}}/{{urlPath}}/chat/message/remove-chat-users
Content-Type: application/json
Accept: application/json
withCredentials: true
# user one is the loged in user usertwo is the one you want to add to the chat
{
  "userOne": "",
  "userTwo": ""
}

###
PUT {{baseUrl}}/{{urlPath}}/chat/message/mark-as-read
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "senderId": "",
  "receiverId": ""
}

###
PUT {{baseUrl}}/{{urlPath}}/chat/message/reaction
Content-Type: application/json
Accept: application/json
withCredentials: true

# For this endpoint, the type is either add or remove
{
  "conversationId": "",
  "messageId": "",
  "reaction": "",
  "type": ""
}

###
DELETE {{baseUrl}}/{{urlPath}}/chat/message/mark-as-deleted/<messageId>/<senderId>/<receiverId>/<type>
# For this endpoint, the type is either deleteForMe or deleteForEveryone
Content-Type: application/json
Accept: application/json
withCredentials: true
