@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/comment
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "64da78556dc5bcbcd97ba4c7",
  "postId": "64fb0c419d8bbe07ab8aa7f7",
  "comment": "This is my test comment 3",
  "profilePicture": "https://res.cloudinary.com/doyg3ppyn/image/upload/v1688363053/64a2602c69ce7813cd2f9fa2.png"
}


###
GET {{baseUrl}}/{{urlPath}}/post/commentsnames/64fb0c419d8bbe07ab8aa7f7
Content-Type: application/json
Accept: application/json
withCredentials: true


###
GET {{baseUrl}}/{{urlPath}}/post/single/comment/64fb0c419d8bbe07ab8aa7f7/64fb0f069d8bbe07ab8aa811
Content-Type: application/json
Accept: application/json
withCredentials: true
