@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/reaction
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "64da78556dc5bcbcd97ba4c7",
  "postId": "64fb0c419d8bbe07ab8aa7f7",
  "type": "like",
  "previousReaction": "",
  "postReactions": {"like":1,"love":0,"happy":0,"sad":0,"wow":0,"angry":0},
  "profilePicture": "https://res.cloudinary.com/doyg3ppyn/image/upload/v1688363053/64a2602c69ce7813cd2f9fa2.png"
}


###
DELETE  {{baseUrl}}/{{urlPath}}/post/reaction/64fb0c419d8bbe07ab8aa7f7/like/{"like":0,"love":0,"happy":0,"sad":0,"wow":0,"angry":0}
Content-Type: application/json
Accept: application/json
withCredentials: true

{}


###
GET {{baseUrl}}/{{urlPath}}/post/reactions/64fb0c419d8bbe07ab8aa7f7/
Content-Type: application/json
Accept: application/json
withCredentials: true


###
GET {{baseUrl}}/{{urlPath}}/post/single/reaction/username/drilll/64fb0c419d8bbe07ab8aa7f7
Content-Type: application/json
Accept: application/json
withCredentials: true


###
GET {{baseUrl}}/{{urlPath}}/post/reactions/username/drilll
Content-Type: application/json
Accept: application/json
withCredentials: true
